name: Feature Request
description: Suggest a feature or idea for this project
assignees: "Jerrie-Aries"
title: "[FEATURE] feature title"
labels: "Feature request"
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What plugin is the feature request for?
      multiple: true
      options:
        - Announcement
        - Embed Manager
        - Extended Utils
        - Giveaway
        - Invites
        - Keepalive
        - Logviewer
        - Moderation
        - Role Manager
        - Support Utility
        - Trivia
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: The Problem
      description: >
        What problem is your feature trying to solve?
        What becomes easier or possible when this feature is implemented?
  - type: textarea
    attributes:
      label: The Ideal Solution
      description: >
        What is your ideal solution to the problem?
        What would you like this feature to do?
  - type: textarea
    attributes:
      label: The Current Solution
      description: >
        What is the current solution to the problem, if any?
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
